### ISSUE TITLE
Discussion: Move "Hosting & Deployment" articles out of docs

### ISSUE THREAD

**Issue by budparr** [rdwatters/hugo-docs-concept#101]
Goals
1) Trying to cut back the docs as much as possible. 
2) Not endorse particular commercial services in an "official" way.

I'd love to get "Hosting & Deployment" off top level menu and create a page within the tools(?) section that references all of them, and then publish those pages on the (arguably) less formal blog. 

Thoughts?

**Comment by rdwatters** [comment]
I see what you're saying, but I don' think the docs are actually *that* long. I'd like to just keep it to the most popular and beginner-friendly hosting/deployment solutions. I'm not saying rsync is especially sophisticated, but we can probably get rid of that page.

> create a page within the tools(?) 

I like the logic on this, but I worry about creating more list pages (i.e., lists of links and not necessarily a Hugo `list.html`) that act as quasi-SERPs rather than substantive content. If we move these pages to the blog, they transition from "guides" to "posts," which means they are less likely to be updated by users. The GH Pages, Wercker, and Netlify guides are up to date because of multiple PRs and issues. I think our readership is much less likely to participate in the maintenance of this content when presented as a blog post, especially if we are going the route of displaying individual authorship.

If we are talking more about limiting the number of H/D pages, what would you suggest? Seems like GH, Gitlab, Netlify, and S3 are all really common, but I think you have much more experience with these providers.

Thanks @budparr!

**Comment by budparr** [comment]
Sorry, I guess I wasn't very clear. When I said "Trying to cut back the docs as much as possible." I meant cut back on the top-level menu items. I think the menu will be most useful if it's really focused on Hugo, not static stuff in general. Having been recently new to Hugo, I've experienced having to wade through all those menu items. I really want to reduce the noise as much as possible here.

When I said "create a page within the tools(?)" I meant, within the "Tools" section create a single page that is called "Hosting and Deploument" that says "hey, static sites are easy to host and deploy. Here are the most basic methods, and we have some blog posts about other solutions, here are links to a few of them..." and link out to blog posts, or original sources

---

The reason I advocate for putting the solutions (e.g. GH, Gitlab, etc) on the blog is that:

1) As Hugo becomes more popular, and static becomes more mainstream, there will be many more commercial hosting solutions (there already are, actually). Who chooses which ones go on there when the businesses ask to be listed? Do we test/vet each one before we list it? Who is responsible for that? If we don't vet, then we just end up with a big list, like the current showcase, which has little to no meaning and serves counter to its purpose. So, if Forge, Surge, Now all want to be listed (perfectly good services, I think, that we're missing), do we list them as well in our official documentation?

2) I personally don't think an open source project should advocate for particular businesses in their documentation. 

3) We are providing instructions for a commercial service that may or may not change over time (I think the Bitbucket/Aerobatic relationship has changed so those instructions may very well be outdated already). Whose responsibility is it to keep these other services protocols up-to-date? I don't think it should be the responsibility of this project. Blog posts aren't official documentation, so have less onus on being kept up-to-date.

**Comment by rdwatters** [comment]
All good points :smile: :

> I personally don't think an open source project should advocate for particular businesses in their documentation.

I agree wholeheartedly, but we are already including the Netlify logo in the bottom right, so I don't have a problem including some screenshots and Hugo-specific walkthroughs for this service. I think they've been very generous to us (and at the risk of solipsism, to me in particular). We also have the Algolia logo as a requirement for using the free service.

> Whose responsibility is it to keep these other services protocols up-to-date?

The community has been good about updating the docs for GH, Wercker, etc, and it's tough to find these resources elsewhere, at least in a very Hugo-specific manner. We could limit it to only "free" services and services that offer a free tier. Many of the new commercial services also offer a CMS layer, which is something I'd like to avoid entirely. We've also had a fair number of threads related to hosting and deployment on the forums over the last 18 months, and I'd rather avoid future versions of such threads via solid documentation for a few basic options. I'm all for pointing users to fill-in-the-blank forum, but there are times where said forum doesn't exist.

I'm getting to be a bit of a broken record here, but really this boils down to the same question I've had since the beginning: who are our primary, secondary, and tertiary audiences for the site? There are political, ethical, resource-driven, and technical reasons to include or omit content, but until we can speak on behalf of a target user, it's all just opinion and hearsay.

I've assumed we are targeting "beginners," in which case I think it's still good to have walkthroughs for simple, popular, free hosting solutions. Jekyll needs to worry about this less because it's inseparably wedded to, and generously supported by, GitHub. Hugo does not have this luxury.

> If we don't vet, then we just end up with a big list, like the current showcase, which has little to no meaning and serves counter to its purpose. 

Right, you'll never hear me saying that vetting is a bad thing :smile: I think the showcase is of a much different scope, and I've said for at least a couple months that we should get rid of it, move it to a forum channel, or even break it off into it's own property.

Also note that I got rid of the "Tutorials" section for the same reasons you've mentioned, and I've done my best to remove the superfluous content from some of the other walkthroughs, although there is still more chaff to separate from the wheat.

> Blog posts aren't official documentation, so have less onus on being kept up-to-date.

If the issue is that we shouldn't be endorsing commercial services in the documentation, then I think the same would extend to the blog, no? A blog post written by a Hugo team member is still an endorsement, which means we will likely get forum threads about outdated blog posts that could otherwise be updated by the community as part of the docs.

If we want to steer clear of endorsing any commercial services according to your metric, we have to delete a lot more than just Hosting and Deployment from the docs. More importantly, we will have to limit the scope of the blog to only discussions from the team about Hugo releases and features, which I'm not saying is necessarily a bad idea. In fact, it's an entirely viable, and common, approach, so I'm open to taking this route if you think it's best.

As far as moving H/D out of the main navigation, I'm open to suggestions as long as we keep the majority of the content intact. Are you thinking maybe a nested section under Tools?

> Having been recently new to Hugo, I've experienced having to wade through all those menu items.

I think we should work on users being able to directly link to any page on the site within the navigation then. I've said this before, but I think this is the best docs site I've ever used:

https://vuejs.org/v2/guide/

It also has about 30 sections *just for the guide*. I think the argument that a navigation "has too many items" as an argument for things being hard to find is not well supported in the wild. The reason people can't find what they're looking for on gohugo.io, IMHO, is because our largest section is "Extras" (this begs the question of what "extra" means) and the order of the sections and pages is counterintuitive, especially for beginners. Maybe we can rework things once Hugo has support for nested sections as well? Thoughts?

I think it's important to keep in mind that compared to many doc sites, hugodocs.info is actually pretty terse.

Thoughts?

**Comment by budparr** [comment]
If you all are comfortable advocating these services, it's fine by me. I'm trying to take the long view here and have stated my opinion.

I'm already re-thinking menu structure, which will help my other reason (as a designer, I shouldn't be trying to dictate content anyway, I should be taking the constraints as I'm given them :) ).

FWIW IMHO, the vue docs aren't particularly remarkable.

**Comment by rdwatters** [comment]
> as a designer, I shouldn't be trying to dictate content anyway, I should be taking the constraints as I'm given them

I think of you as more than just a designer, and I know you have content expertise, so I legitimately appreciate the feedback :smile:

> FWIW IMHO, the vue docs aren't particularly remarkable.

As far as design or content? If design, I agree. They're really simple and unremarkable. But I think the content, visualizations, explanations, writing, examples, etc are fantastic, and I've gone through the docs of every major JS MVwhatever at this point. 

(You don't have to answer this with everything else going on. I'm just curious.)

**Comment by budparr** [comment]
I was thinking of the design (re: vue docs), because I thought you were too. I've never read the content.
