### ISSUE TITLE
Updates to front matter variables

### ISSUE THREAD

**Issue by moorereason** [rdwatters/hugo-docs-concept#29]
As seen here: https://hugodocs.info/content-management/front-matter/#front-matter-variables

*Note: these are surely issues in the upstream docs, but I don't want us to have to do double work.  I'm confident this site will eventually replace the existing docs site.*

- There are no required front matter variables anymore.  No need to differentiate required/optional variables.  Technically, the entire front matter section is optional now.

- The list of page variables is incomplete.  See [hugolib.Page.update()](https://github.com/spf13/hugo/blob/ede452d34ef82a2d6949bf0c5a4584caf3ae03bc/hugolib/page.go#L985) for the full list of reserved front matter variables.

**Comment by rdwatters** [comment]
@moorereason I've [finished most of these](https://hugodocs.info/content-management/front-matter/#predefined). I'm assuming [`published`](https://github.com/spf13/hugo/blob/ede452d34ef82a2d6949bf0c5a4584caf3ae03bc/hugolib/page.go#L1039) is still intentionally undocumented because of potential confusion over its [relationship with `draft`](https://github.com/spf13/hugo/blob/ede452d34ef82a2d6949bf0c5a4584caf3ae03bc/hugolib/page.go#L1110)?

`status`, `ext`, and `sitemap` will have to wait until tomorrow.

**Comment by rdwatters** [comment]
closing this since the front matter section is updated; `status` is a non-issue and neither are the aliases in the current code.
